module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'addresses',
      [
        {
          number: 36754,
          address: '5523 nolan brook',
          neighborhood: 'apt. 983',
          city: 'north sophia',
          state: 'arizona',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'holy see (vatican city state)',
        },
        {
          number: 74397,
          address: '2034 friesen village',
          neighborhood: 'apt. 510',
          city: 'mantehaven',
          state: 'massachusetts',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'nicaragua',
        },
        {
          number: 63702,
          address: '5904 karley viaduct',
          neighborhood: 'apt. 743',
          city: 'east darron',
          state: 'maryland',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'tuvalu',
        },
        {
          number: 99418,
          address: '5583 francis views',
          neighborhood: 'apt. 966',
          city: 'new euna',
          state: 'kansas',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'saint martin',
        },
        {
          number: 25672,
          address: '812 florine throughway',
          neighborhood: 'apt. 398',
          city: 'north ebbaberg',
          state: 'nebraska',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'japan',
        },
        {
          number: 24668,
          address: '83174 dasia bypass',
          neighborhood: 'suite 307',
          city: 'bechtelartown',
          state: 'west virginia',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'united states minor outlying islands',
        },
        {
          number: 95449,
          address: '894 aiden stravenue',
          neighborhood: 'apt. 114',
          city: 'south ena',
          state: 'kansas',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'bhutan',
        },
        {
          number: 35573,
          address: '90826 bernier heights',
          neighborhood: 'suite 422',
          city: 'south rae',
          state: 'ohio',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'maldives',
        },
        {
          number: 59857,
          address: '52973 prosacco forks',
          neighborhood: 'apt. 479',
          city: 'north korbinview',
          state: 'utah',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'pitcairn islands',
        },
        {
          number: 10098,
          address: '42381 bednar port',
          neighborhood: 'suite 973',
          city: 'emmerichshire',
          state: 'florida',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'guinea-bissau',
        },
        {
          number: 98716,
          address: '18158 rutherford union',
          neighborhood: 'apt. 979',
          city: 'myrlland',
          state: 'iowa',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'afghanistan',
        },
        {
          number: 40989,
          address: '7370 eloisa mill',
          neighborhood: 'suite 202',
          city: 'new robbshire',
          state: 'georgia',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'tunisia',
        },
        {
          number: 38502,
          address: '6558 rosamond heights',
          neighborhood: 'suite 057',
          city: 'south frederick',
          state: 'vermont',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'isle of man',
        },
        {
          number: 81565,
          address: '36388 fabian crescent',
          neighborhood: 'apt. 760',
          city: 'blandaland',
          state: 'montana',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'belarus',
        },
        {
          number: 79096,
          address: '1631 edison cape',
          neighborhood: 'apt. 278',
          city: 'east jarrell',
          state: 'delaware',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'pitcairn islands',
        },
        {
          number: 9101,
          address: '43641 hane inlet',
          neighborhood: 'apt. 448',
          city: 'veumhaven',
          state: 'missouri',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'estonia',
        },
        {
          number: 68256,
          address: '94033 erdman knoll',
          neighborhood: 'suite 309',
          city: 'prestontown',
          state: 'connecticut',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'yemen',
        },
        {
          number: 95641,
          address: '377 stamm ridges',
          neighborhood: 'suite 743',
          city: 'rhiannonville',
          state: 'oklahoma',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'france',
        },
        {
          number: 81895,
          address: '341 koch track',
          neighborhood: 'suite 166',
          city: 'verdiechester',
          state: 'hawaii',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'central african republic',
        },
        {
          number: 63156,
          address: '377 wyman lodge',
          neighborhood: 'apt. 667',
          city: 'schummburgh',
          state: 'texas',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'philippines',
        },
        {
          number: 66957,
          address: '61556 corkery views',
          neighborhood: 'apt. 532',
          city: 'jewellport',
          state: 'nebraska',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'northern mariana islands',
        },
        {
          number: 10396,
          address: '904 danika valley',
          neighborhood: 'apt. 674',
          city: 'new earlineland',
          state: 'connecticut',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'latvia',
        },
        {
          number: 7951,
          address: '000 cummerata parks',
          neighborhood: 'suite 543',
          city: 'port annettaton',
          state: 'north dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'china',
        },
        {
          number: 75425,
          address: '59226 lexie crescent',
          neighborhood: 'apt. 417',
          city: 'south celestinoton',
          state: 'minnesota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'aruba',
        },
        {
          number: 49563,
          address: "3428 o'conner haven",
          neighborhood: 'apt. 953',
          city: 'west carissa',
          state: 'alaska',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'turkey',
        },
        {
          number: 82145,
          address: '18802 roberts manor',
          neighborhood: 'suite 629',
          city: 'west hildegardshire',
          state: 'mississippi',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'italy',
        },
        {
          number: 75091,
          address: '0280 orn mission',
          neighborhood: 'apt. 786',
          city: 'brennanland',
          state: 'new york',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'nepal',
        },
        {
          number: 78235,
          address: '62978 tromp ways',
          neighborhood: 'apt. 869',
          city: 'east odessachester',
          state: 'wyoming',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'slovakia (slovak republic)',
        },
        {
          number: 72701,
          address: '21848 abernathy gateway',
          neighborhood: 'suite 236',
          city: 'donnellyside',
          state: 'new jersey',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'gambia',
        },
        {
          number: 75548,
          address: '841 lindgren ramp',
          neighborhood: 'suite 727',
          city: 'chadricktown',
          state: 'utah',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'cambodia',
        },
        {
          number: 61481,
          address: '987 bergnaum walks',
          neighborhood: 'apt. 988',
          city: 'new linda',
          state: 'louisiana',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'antigua and barbuda',
        },
        {
          number: 95990,
          address: '7034 abbott keys',
          neighborhood: 'suite 856',
          city: 'cristinashire',
          state: 'maryland',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'guinea-bissau',
        },
        {
          number: 41839,
          address: '5125 mills freeway',
          neighborhood: 'apt. 055',
          city: 'port clarabelle',
          state: 'florida',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'germany',
        },
        {
          number: 64393,
          address: '13390 sipes brook',
          neighborhood: 'apt. 128',
          city: 'lake hipolito',
          state: 'alabama',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'kazakhstan',
        },
        {
          number: 64903,
          address: "2464 o'keefe ranch",
          neighborhood: 'suite 867',
          city: 'port adellhaven',
          state: 'california',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'micronesia',
        },
        {
          number: 24451,
          address: '402 elmira river',
          neighborhood: 'suite 959',
          city: 'wunschmouth',
          state: 'massachusetts',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'poland',
        },
        {
          number: 85764,
          address: '1546 powlowski islands',
          neighborhood: 'suite 045',
          city: 'port linashire',
          state: 'colorado',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'nauru',
        },
        {
          number: 34990,
          address: '4855 bradtke streets',
          neighborhood: 'apt. 408',
          city: 'padbergfort',
          state: 'california',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'belgium',
        },
        {
          number: 74383,
          address: '89726 rod mission',
          neighborhood: 'apt. 662',
          city: 'west angel',
          state: 'wyoming',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'rwanda',
        },
        {
          number: 6570,
          address: '1708 sanford road',
          neighborhood: 'suite 773',
          city: 'faheyshire',
          state: 'illinois',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'colombia',
        },
        {
          number: 34004,
          address: '5950 russel tunnel',
          neighborhood: 'apt. 726',
          city: 'new keaton',
          state: 'california',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'virgin islands, british',
        },
        {
          number: 52307,
          address: '6261 juston loaf',
          neighborhood: 'apt. 145',
          city: 'brucebury',
          state: 'alabama',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'burundi',
        },
        {
          number: 29389,
          address: '1558 elliott locks',
          neighborhood: 'apt. 865',
          city: 'lake tremayne',
          state: 'nebraska',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'cyprus',
        },
        {
          number: 14908,
          address: '33407 samara estates',
          neighborhood: 'apt. 839',
          city: 'east camillestad',
          state: 'ohio',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'kuwait',
        },
        {
          number: 25779,
          address: '765 thurman mountains',
          neighborhood: 'suite 495',
          city: 'lake earlineport',
          state: 'minnesota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'peru',
        },
        {
          number: 27987,
          address: '543 orn fork',
          neighborhood: 'suite 224',
          city: 'port aubreestad',
          state: 'alabama',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'saint lucia',
        },
        {
          number: 75655,
          address: '87776 batz dale',
          neighborhood: 'apt. 812',
          city: 'north leannafurt',
          state: 'louisiana',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'china',
        },
        {
          number: 90206,
          address: '9599 kohler mount',
          neighborhood: 'apt. 194',
          city: 'lake aureliamouth',
          state: 'georgia',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'sierra leone',
        },
        {
          number: 48180,
          address: '08128 mayert pass',
          neighborhood: 'apt. 499',
          city: 'kristastad',
          state: 'new jersey',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'slovenia',
        },
        {
          number: 10111,
          address: '51231 ari roads',
          neighborhood: 'apt. 547',
          city: 'port lizamouth',
          state: 'michigan',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'romania',
        },
        {
          number: 82684,
          address: '61823 wuckert trace',
          neighborhood: 'apt. 926',
          city: 'south ezra',
          state: 'california',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'switzerland',
        },
        {
          number: 17550,
          address: '047 thiel harbor',
          neighborhood: 'apt. 661',
          city: 'east hobartmouth',
          state: 'oregon',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'italy',
        },
        {
          number: 12035,
          address: '578 bergnaum parkway',
          neighborhood: 'suite 455',
          city: 'lake jaylan',
          state: 'arkansas',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'antigua and barbuda',
        },
        {
          number: 96851,
          address: '6374 wuckert oval',
          neighborhood: 'suite 005',
          city: 'johnport',
          state: 'south dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'ethiopia',
        },
        {
          number: 35044,
          address: '04234 lloyd port',
          neighborhood: 'suite 229',
          city: 'fatimastad',
          state: 'delaware',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'libyan arab jamahiriya',
        },
        {
          number: 32897,
          address: "32248 o'reilly green",
          neighborhood: 'suite 532',
          city: 'new kayleebury',
          state: 'south dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'lesotho',
        },
        {
          number: 8863,
          address: '405 carli landing',
          neighborhood: 'apt. 154',
          city: 'south juston',
          state: 'maine',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'bulgaria',
        },
        {
          number: 69070,
          address: '0516 armando estate',
          neighborhood: 'apt. 270',
          city: 'elliechester',
          state: 'pennsylvania',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'senegal',
        },
        {
          number: 40835,
          address: '41259 weissnat mount',
          neighborhood: 'suite 636',
          city: 'marvinberg',
          state: 'michigan',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'argentina',
        },
        {
          number: 94608,
          address: '947 chandler lodge',
          neighborhood: 'apt. 949',
          city: 'north abe',
          state: 'south carolina',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'nepal',
        },
        {
          number: 14970,
          address: '34756 runolfsdottir ramp',
          neighborhood: 'apt. 684',
          city: 'east cyrushaven',
          state: 'utah',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'singapore',
        },
        {
          number: 5855,
          address: '1038 olson loop',
          neighborhood: 'apt. 311',
          city: 'north sydni',
          state: 'oklahoma',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: 1,
          country: 'vietnam',
        },
        {
          number: 90762,
          address: '95170 rosella fields',
          neighborhood: 'suite 327',
          city: 'north eliseo',
          state: 'washington',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'brunei darussalam',
        },
        {
          number: 2722,
          address: '04895 tierra freeway',
          neighborhood: 'suite 191',
          city: 'runolfssonborough',
          state: 'north dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: "cote d'ivoire",
        },
        {
          number: 39489,
          address: '40600 steuber lake',
          neighborhood: 'apt. 124',
          city: 'stacyhaven',
          state: 'michigan',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'malawi',
        },
        {
          number: 70090,
          address: '0159 aurore ridges',
          neighborhood: 'apt. 339',
          city: 'lucieton',
          state: 'ohio',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'croatia',
        },
        {
          number: 81198,
          address: '176 winston loop',
          neighborhood: 'apt. 296',
          city: 'lake cordie',
          state: 'ohio',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'norfolk island',
        },
        {
          number: 14025,
          address: '2907 carmel rue',
          neighborhood: 'apt. 236',
          city: 'maggioberg',
          state: 'alabama',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'morocco',
        },
        {
          number: 69069,
          address: "0702 o'kon junction",
          neighborhood: 'apt. 480',
          city: 'west hans',
          state: 'north carolina',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'tonga',
        },
        {
          number: 60293,
          address: '5126 shania roads',
          neighborhood: 'suite 596',
          city: 'ulicesborough',
          state: 'washington',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'sao tome and principe',
        },
        {
          number: 43743,
          address: '279 bahringer gardens',
          neighborhood: 'suite 041',
          city: 'lisaborough',
          state: 'virginia',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'ghana',
        },
        {
          number: 21053,
          address: '1294 gretchen pine',
          neighborhood: 'apt. 834',
          city: 'santosview',
          state: 'south dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'singapore',
        },
        {
          number: 4613,
          address: '6404 bergnaum prairie',
          neighborhood: 'apt. 756',
          city: 'north autumnmouth',
          state: 'new hampshire',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'netherlands',
        },
        {
          number: 36539,
          address: '40903 reilly pass',
          neighborhood: 'suite 119',
          city: 'south maximus',
          state: 'oklahoma',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'grenada',
        },
        {
          number: 88322,
          address: '90574 will camp',
          neighborhood: 'suite 052',
          city: 'keirastad',
          state: 'south carolina',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'namibia',
        },
        {
          number: 70135,
          address: '419 zander trace',
          neighborhood: 'apt. 982',
          city: 'north gudruntown',
          state: 'new york',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'anguilla',
        },
        {
          number: 45741,
          address: '51452 zboncak harbors',
          neighborhood: 'apt. 482',
          city: 'west elmirachester',
          state: 'north dakota',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'iceland',
        },
        {
          number: 32424,
          address: '752 glover crossing',
          neighborhood: 'apt. 369',
          city: 'powlowskifort',
          state: 'rhode island',
          created_at: new Date(),
          updated_at: new Date(),
          zipcode: '12345678',
          fk_contact_id: Math.floor(Math.random() * 75) + 1,
          country: 'cambodia',
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('addresses', null, {});
  },
};
